from .user import user_bp
from .jewelry import jewelry_bp
from .materials import materials_bp
from .patterns import patterns_bp
from .stones import stones_bp
from .dashboard import dashboard_bp
from .employees import employees_bp
from .vales import vales_bp
from .payments import payments_bp
from .caixa import caixa_bp
from .costs import costs_bp
from .financial import financial_bp
from .inventory import inventory_bp
from .notas import notas_bp
from .orders import orders_bp
from .payroll import payroll_bp
